// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvoiceStatus int32

const (
	InvoiceStatus_INVOICE_STATUS_UNSPECIFIED InvoiceStatus = 0
	InvoiceStatus_OPEN                       InvoiceStatus = 1
	InvoiceStatus_CLOSED                     InvoiceStatus = 2
	InvoiceStatus_PAID                       InvoiceStatus = 3
	InvoiceStatus_VOID                       InvoiceStatus = 4
)

// Enum value maps for InvoiceStatus.
var (
	InvoiceStatus_name = map[int32]string{
		0: "INVOICE_STATUS_UNSPECIFIED",
		1: "OPEN",
		2: "CLOSED",
		3: "PAID",
		4: "VOID",
	}
	InvoiceStatus_value = map[string]int32{
		"INVOICE_STATUS_UNSPECIFIED": 0,
		"OPEN":                       1,
		"CLOSED":                     2,
		"PAID":                       3,
		"VOID":                       4,
	}
)

func (x InvoiceStatus) Enum() *InvoiceStatus {
	p := new(InvoiceStatus)
	*p = x
	return p
}

func (x InvoiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_v1_billing_proto_enumTypes[0].Descriptor()
}

func (InvoiceStatus) Type() protoreflect.EnumType {
	return &file_billing_v1_billing_proto_enumTypes[0]
}

func (x InvoiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoiceStatus.Descriptor instead.
func (InvoiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

type LineKind int32

const (
	LineKind_LINE_KIND_UNSPECIFIED LineKind = 0
	LineKind_BOOKING               LineKind = 1
	LineKind_HOURLY                LineKind = 2
	LineKind_OVERNIGHT             LineKind = 3
	LineKind_CANCELLATION          LineKind = 4
	LineKind_NOSHOW                LineKind = 5
)

// Enum value maps for LineKind.
var (
	LineKind_name = map[int32]string{
		0: "LINE_KIND_UNSPECIFIED",
		1: "BOOKING",
		2: "HOURLY",
		3: "OVERNIGHT",
		4: "CANCELLATION",
		5: "NOSHOW",
	}
	LineKind_value = map[string]int32{
		"LINE_KIND_UNSPECIFIED": 0,
		"BOOKING":               1,
		"HOURLY":                2,
		"OVERNIGHT":             3,
		"CANCELLATION":          4,
		"NOSHOW":                5,
	}
)

func (x LineKind) Enum() *LineKind {
	p := new(LineKind)
	*p = x
	return p
}

func (x LineKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LineKind) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_v1_billing_proto_enumTypes[1].Descriptor()
}

func (LineKind) Type() protoreflect.EnumType {
	return &file_billing_v1_billing_proto_enumTypes[1]
}

func (x LineKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LineKind.Descriptor instead.
func (LineKind) EnumDescriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

type LineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          LineKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=parkirpintar.billing.v1.LineKind" json:"kind,omitempty"`
	AmountIdr     int64                  `protobuf:"varint,3,opt,name=amount_idr,json=amountIdr,proto3" json:"amount_idr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *LineItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LineItem) GetKind() LineKind {
	if x != nil {
		return x.Kind
	}
	return LineKind_LINE_KIND_UNSPECIFIED
}

func (x *LineItem) GetAmountIdr() int64 {
	if x != nil {
		return x.AmountIdr
	}
	return 0
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        InvoiceStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=parkirpintar.billing.v1.InvoiceStatus" json:"status,omitempty"`
	TotalIdr      int64                  `protobuf:"varint,4,opt,name=total_idr,json=totalIdr,proto3" json:"total_idr,omitempty"`
	Lines         []*LineItem            `protobuf:"bytes,5,rep,name=lines,proto3" json:"lines,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *Invoice) GetStatus() InvoiceStatus {
	if x != nil {
		return x.Status
	}
	return InvoiceStatus_INVOICE_STATUS_UNSPECIFIED
}

func (x *Invoice) GetTotalIdr() int64 {
	if x != nil {
		return x.TotalIdr
	}
	return 0
}

func (x *Invoice) GetLines() []*LineItem {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Invoice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invoice) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *Invoice) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

type OpenInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenInvoiceRequest) Reset() {
	*x = OpenInvoiceRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenInvoiceRequest) ProtoMessage() {}

func (x *OpenInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenInvoiceRequest.ProtoReflect.Descriptor instead.
func (*OpenInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *OpenInvoiceRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *OpenInvoiceRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type CloseInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	CheckedInAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=checked_in_at,json=checkedInAt,proto3" json:"checked_in_at,omitempty"`
	CheckedOutAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=checked_out_at,json=checkedOutAt,proto3" json:"checked_out_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseInvoiceRequest) Reset() {
	*x = CloseInvoiceRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseInvoiceRequest) ProtoMessage() {}

func (x *CloseInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CloseInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *CloseInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *CloseInvoiceRequest) GetCheckedInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedInAt
	}
	return nil
}

func (x *CloseInvoiceRequest) GetCheckedOutAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedOutAt
	}
	return nil
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *GetInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CreatePaymentReq represents a new booking fee payment request to be created.
type CreatePaymentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"` // ID of the reservation to charge
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`                // Driver's unique identifier
	AmountIdr     int64                  `protobuf:"varint,3,opt,name=amount_idr,json=amountIdr,proto3" json:"amount_idr,omitempty"`            // Booking fee amount in IDR
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`                                    // Payment method: "QRIS" or "CC"
	CcToken       string                 `protobuf:"bytes,5,opt,name=cc_token,json=ccToken,proto3" json:"cc_token,omitempty"`                   // Credit card token (required if method=CC)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentReq) Reset() {
	*x = CreatePaymentReq{}
	mi := &file_billing_v1_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentReq) ProtoMessage() {}

func (x *CreatePaymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentReq.ProtoReflect.Descriptor instead.
func (*CreatePaymentReq) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePaymentReq) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CreatePaymentReq) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CreatePaymentReq) GetAmountIdr() int64 {
	if x != nil {
		return x.AmountIdr
	}
	return 0
}

func (x *CreatePaymentReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreatePaymentReq) GetCcToken() string {
	if x != nil {
		return x.CcToken
	}
	return ""
}

// PaymentRequest represents the result of payment request creation.
type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // Unique ID for this payment request
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                           // Payment method used
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                           // Status: "PENDING", "SUCCESS", "FAILED"
	QrisUrl       string                 `protobuf:"bytes,4,opt,name=qris_url,json=qrisUrl,proto3" json:"qris_url,omitempty"`          // QRIS URL (only if method=QRIS)
	PaymentRef    string                 `protobuf:"bytes,5,opt,name=payment_ref,json=paymentRef,proto3" json:"payment_ref,omitempty"` // Provider-facing reference ID
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`   // Unix timestamp when payment expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_billing_v1_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_v1_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_billing_v1_billing_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PaymentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentRequest) GetQrisUrl() string {
	if x != nil {
		return x.QrisUrl
	}
	return ""
}

func (x *PaymentRequest) GetPaymentRef() string {
	if x != nil {
		return x.PaymentRef
	}
	return ""
}

func (x *PaymentRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_billing_v1_billing_proto protoreflect.FileDescriptor

const file_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x18billing/v1/billing.proto\x12\x17parkirpintar.billing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\bLineItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x04kind\x18\x02 \x01(\x0e2!.parkirpintar.billing.v1.LineKindR\x04kind\x12\x1d\n" +
	"\n" +
	"amount_idr\x18\x03 \x01(\x03R\tamountIdr\"\xff\x02\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12>\n" +
	"\x06status\x18\x03 \x01(\x0e2&.parkirpintar.billing.v1.InvoiceStatusR\x06status\x12\x1b\n" +
	"\ttotal_idr\x18\x04 \x01(\x03R\btotalIdr\x127\n" +
	"\x05lines\x18\x05 \x03(\v2!.parkirpintar.billing.v1.LineItemR\x05lines\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tclosed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x123\n" +
	"\apaid_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"X\n" +
	"\x12OpenInvoiceRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"\xb6\x01\n" +
	"\x13CloseInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12>\n" +
	"\rchecked_in_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcheckedInAt\x12@\n" +
	"\x0echecked_out_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fcheckedOutAt\"#\n" +
	"\x11GetInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa8\x01\n" +
	"\x10CreatePaymentReq\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x1d\n" +
	"\n" +
	"amount_idr\x18\x03 \x01(\x03R\tamountIdr\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x19\n" +
	"\bcc_token\x18\x05 \x01(\tR\accToken\"\xab\x01\n" +
	"\x0ePaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\bqris_url\x18\x04 \x01(\tR\aqrisUrl\x12\x1f\n" +
	"\vpayment_ref\x18\x05 \x01(\tR\n" +
	"paymentRef\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt*Y\n" +
	"\rInvoiceStatus\x12\x1e\n" +
	"\x1aINVOICE_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04OPEN\x10\x01\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x02\x12\b\n" +
	"\x04PAID\x10\x03\x12\b\n" +
	"\x04VOID\x10\x04*k\n" +
	"\bLineKind\x12\x19\n" +
	"\x15LINE_KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aBOOKING\x10\x01\x12\n" +
	"\n" +
	"\x06HOURLY\x10\x02\x12\r\n" +
	"\tOVERNIGHT\x10\x03\x12\x10\n" +
	"\fCANCELLATION\x10\x04\x12\n" +
	"\n" +
	"\x06NOSHOW\x10\x052\x96\x03\n" +
	"\x0eBillingService\x12\\\n" +
	"\vOpenInvoice\x12+.parkirpintar.billing.v1.OpenInvoiceRequest\x1a .parkirpintar.billing.v1.Invoice\x12^\n" +
	"\fCloseInvoice\x12,.parkirpintar.billing.v1.CloseInvoiceRequest\x1a .parkirpintar.billing.v1.Invoice\x12Z\n" +
	"\n" +
	"GetInvoice\x12*.parkirpintar.billing.v1.GetInvoiceRequest\x1a .parkirpintar.billing.v1.Invoice\x12j\n" +
	"\x14CreatePaymentRequest\x12).parkirpintar.billing.v1.CreatePaymentReq\x1a'.parkirpintar.billing.v1.PaymentRequestBAZ?github.com/farid/billing-service/api/proto/billing/v1;billingv1b\x06proto3"

var (
	file_billing_v1_billing_proto_rawDescOnce sync.Once
	file_billing_v1_billing_proto_rawDescData []byte
)

func file_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)))
	})
	return file_billing_v1_billing_proto_rawDescData
}

var file_billing_v1_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_billing_v1_billing_proto_goTypes = []any{
	(InvoiceStatus)(0),            // 0: parkirpintar.billing.v1.InvoiceStatus
	(LineKind)(0),                 // 1: parkirpintar.billing.v1.LineKind
	(*LineItem)(nil),              // 2: parkirpintar.billing.v1.LineItem
	(*Invoice)(nil),               // 3: parkirpintar.billing.v1.Invoice
	(*OpenInvoiceRequest)(nil),    // 4: parkirpintar.billing.v1.OpenInvoiceRequest
	(*CloseInvoiceRequest)(nil),   // 5: parkirpintar.billing.v1.CloseInvoiceRequest
	(*GetInvoiceRequest)(nil),     // 6: parkirpintar.billing.v1.GetInvoiceRequest
	(*CreatePaymentReq)(nil),      // 7: parkirpintar.billing.v1.CreatePaymentReq
	(*PaymentRequest)(nil),        // 8: parkirpintar.billing.v1.PaymentRequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_billing_v1_billing_proto_depIdxs = []int32{
	1,  // 0: parkirpintar.billing.v1.LineItem.kind:type_name -> parkirpintar.billing.v1.LineKind
	0,  // 1: parkirpintar.billing.v1.Invoice.status:type_name -> parkirpintar.billing.v1.InvoiceStatus
	2,  // 2: parkirpintar.billing.v1.Invoice.lines:type_name -> parkirpintar.billing.v1.LineItem
	9,  // 3: parkirpintar.billing.v1.Invoice.created_at:type_name -> google.protobuf.Timestamp
	9,  // 4: parkirpintar.billing.v1.Invoice.closed_at:type_name -> google.protobuf.Timestamp
	9,  // 5: parkirpintar.billing.v1.Invoice.paid_at:type_name -> google.protobuf.Timestamp
	9,  // 6: parkirpintar.billing.v1.CloseInvoiceRequest.checked_in_at:type_name -> google.protobuf.Timestamp
	9,  // 7: parkirpintar.billing.v1.CloseInvoiceRequest.checked_out_at:type_name -> google.protobuf.Timestamp
	4,  // 8: parkirpintar.billing.v1.BillingService.OpenInvoice:input_type -> parkirpintar.billing.v1.OpenInvoiceRequest
	5,  // 9: parkirpintar.billing.v1.BillingService.CloseInvoice:input_type -> parkirpintar.billing.v1.CloseInvoiceRequest
	6,  // 10: parkirpintar.billing.v1.BillingService.GetInvoice:input_type -> parkirpintar.billing.v1.GetInvoiceRequest
	7,  // 11: parkirpintar.billing.v1.BillingService.CreatePaymentRequest:input_type -> parkirpintar.billing.v1.CreatePaymentReq
	3,  // 12: parkirpintar.billing.v1.BillingService.OpenInvoice:output_type -> parkirpintar.billing.v1.Invoice
	3,  // 13: parkirpintar.billing.v1.BillingService.CloseInvoice:output_type -> parkirpintar.billing.v1.Invoice
	3,  // 14: parkirpintar.billing.v1.BillingService.GetInvoice:output_type -> parkirpintar.billing.v1.Invoice
	8,  // 15: parkirpintar.billing.v1.BillingService.CreatePaymentRequest:output_type -> parkirpintar.billing.v1.PaymentRequest
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_billing_v1_billing_proto_init() }
func file_billing_v1_billing_proto_init() {
	if File_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_v1_billing_proto_rawDesc), len(file_billing_v1_billing_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_billing_v1_billing_proto_depIdxs,
		EnumInfos:         file_billing_v1_billing_proto_enumTypes,
		MessageInfos:      file_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_billing_v1_billing_proto = out.File
	file_billing_v1_billing_proto_goTypes = nil
	file_billing_v1_billing_proto_depIdxs = nil
}
